// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;
namespace Pokkt
{
	public class PokktConfig
	{
		//common
		private String applicationId = "";
		private String securityKey = "";
		private PokktIntegrationType integrationType = PokktIntegrationType.INTEGRATION_TYPE_ALL;
		private bool autoCacheVideo = true;
		private String thirdPartyUserId = "";
		
		// offer wall specific
		private String offerWallAssetValue = "";
		private bool closeOnSuccessFlag = false;
		
		// video campaign specific
		private bool skipEnabled = false;
		private int defaultSkipTime = 0;
		private String customSkipMessage = "";
		private String screenName = "Default";
		private bool incentivised = true;
		private bool backButtonDisabled = false;

		// OPTIONAL PARAMS
		private string name;
		private string age;
		private string sex;
		private string mobileNo;
		private string emailAddress;
		private string location;
		private string birthday;
		private string maritalStatus;
		private string facebookId;
		private string twitterHandle;
		private string education;
		private string nationality;
		private string employment;
		private string maturityRating;

		public PokktConfig ()
		{
		}

		public String getApplicationId() {
			return applicationId;
		}
		
		public void setApplicationId(String applicationId) {
			this.applicationId = applicationId;
		}
		
		public String getSecurityKey() {
			return securityKey;
		}
		
		public void setSecurityKey(String securityKey) {
			this.securityKey = securityKey;
		}
		
		public PokktIntegrationType getIntegrationType() {
			return integrationType;
		}
		
		public void setIntegrationType(PokktIntegrationType integrationType) {
			this.integrationType = integrationType;
		}
		
		public bool isAutoCacheVideo() {
			return autoCacheVideo;
		}
		
		public void setAutoCacheVideo(bool autoCacheVideo) {
			this.autoCacheVideo = autoCacheVideo;
		}
		
		public String getThirdPartyUserId() {
			return thirdPartyUserId;
		}
		
		public void setThirdPartyUserId(String thirdPartyUserId) {
			this.thirdPartyUserId = thirdPartyUserId;
			PokktNativeExtension.PerformOperation(PokktOperations.SetThirdPartyUserId, thirdPartyUserId);
		}

		// OFFERWALL METHODS

		public String getOfferWallAssetValue() {
			return offerWallAssetValue;
		}
		
		public void setOfferWallAssetValue(String offerWallAssetValue) {
			this.offerWallAssetValue = offerWallAssetValue;
		}
		
		public bool isCloseOnSuccessFlag() {
			return closeOnSuccessFlag;
		}
		
		public void setCloseOnSuccessFlag(bool closeOnSuccessFlag) {
			this.closeOnSuccessFlag = closeOnSuccessFlag;
			PokktNativeExtension.PerformOperation(PokktOperations.SetCloseOnSuccessFlag, (closeOnSuccessFlag ? "true" : "false"));
		}

		// VIDEO METHODS

		public bool isSkipEnabled() {
			return skipEnabled;
		}
		
		public void setSkipEnabled(bool skipEnabled) {
			this.skipEnabled = skipEnabled;
			PokktNativeExtension.PerformOperation(PokktOperations.SetSkipEnabled, (skipEnabled ? "true" : "false"));
		}
		
		public int getDefaultSkipTime() {
			return defaultSkipTime;
		}
		
		public void setDefaultSkipTime(int defaultSkipTime) {
			this.defaultSkipTime = defaultSkipTime;
			PokktNativeExtension.PerformOperation(PokktOperations.SetDefaultSkipTime, defaultSkipTime+"");
		}
		
		public String getCustomSkipMessage() {
			return customSkipMessage;
		}
		
		public void setCustomSkipMessage(String customSkipMessage) {
			this.customSkipMessage = customSkipMessage;
			PokktNativeExtension.PerformOperation(PokktOperations.SetCustomSkipMessage, customSkipMessage);
		}
		
		public String getScreenName() {
			return screenName;
		}
		
		public void setScreenName(String screenName) {
			this.screenName = screenName;
		}
		
		public bool isIncentivised() {
			return incentivised;
		}
		
		public void setIncentivised(bool incentivised) {
			this.incentivised = incentivised;
		}
		
		public bool isBackButtonDisabled() {
			return backButtonDisabled;
		}
		
		public void setBackButtonDisabled(bool backButtonDisabled) 
		{
			this.backButtonDisabled = backButtonDisabled;
			PokktNativeExtension.PerformOperation(PokktOperations.SetBackButtonDisabled, (backButtonDisabled ? "true" : "false"));
		}

		// OPTIONAL METHODS

		public string getName()
		{
			return name;
		}

		public void setName(string name)
		{
			this.name = name;
			PokktNativeExtension.PerformOperation(PokktOperations.SetName, name);
		}

		public string getAge()
		{
			return age;
		}
		
		public void setAge(string age)
		{
			this.age = age;
			PokktNativeExtension.PerformOperation(PokktOperations.SetAge, age);
		}

		public string getSex()
		{
			return sex;
		}
		
		public void setSex(string sex)
		{
			this.sex = sex;
			PokktNativeExtension.PerformOperation(PokktOperations.SetSex, sex);
		}

		public string getMobileNo()
		{
			return mobileNo;
		}
		
		public void setMobileNo(string mobileNo)
		{
			this.mobileNo = mobileNo;
			PokktNativeExtension.PerformOperation(PokktOperations.SetMobileNo, mobileNo);
		}

		public string getEmailAddress()
		{
			return emailAddress;
		}
		
		public void setEmailAddress(string emailAddress)
		{
			this.emailAddress = emailAddress;
			PokktNativeExtension.PerformOperation(PokktOperations.SetEmailAddress, emailAddress);
		}

		public string getLocation()
		{
			return location;
		}
		
		public void setLocation(string location)
		{
			this.location = location;
			PokktNativeExtension.PerformOperation(PokktOperations.SetLocation, location);
		}

		public string getBirthday()
		{
			return birthday;
		}
		
		public void setBirthday(string birthday)
		{
			this.birthday = birthday;
			PokktNativeExtension.PerformOperation(PokktOperations.SetBirthday);
		}

		public string getMaritalStatus()
		{
			return maritalStatus;
		}
		
		public void setMaritalStatus(string maritalStatus)
		{
			this.maritalStatus = maritalStatus;
			PokktNativeExtension.PerformOperation(PokktOperations.SetMaritalStatus, maritalStatus);
		}

		public string getFacebookId()
		{
			return facebookId;
		}
		
		public void setFacebookId(string facebookId)
		{
			this.facebookId = facebookId;
			PokktNativeExtension.PerformOperation(PokktOperations.SetFacebookId, facebookId);
		}
				
		public string getTwitterHandle()
		{
			return twitterHandle;
		}
		
		public void setTwitterHandle(string twitterHandle)
		{
			this.twitterHandle = twitterHandle;
			PokktNativeExtension.PerformOperation(PokktOperations.SetTwitterHandle, twitterHandle);
		}
		
		public string getEducation()
		{
			return education;
		}
		
		public void setEducation(string education)
		{
			this.education = education;
			PokktNativeExtension.PerformOperation(PokktOperations.SetEducation, education);
		}
		
		public string getNationality()
		{
			return nationality;
		}

		public void setNationality(string nationality)
		{
			this.nationality = nationality;
			PokktNativeExtension.PerformOperation(PokktOperations.SetNationality, nationality);
		}

		public string getEmployment()
		{
			return employment;
		}
		
		public void setEmployment(string employment)
		{
			this.employment = employment;
			PokktNativeExtension.PerformOperation(PokktOperations.SetEmployment, employment);
		}

		public string getMaturityRating()
		{
			return maturityRating;
		}

		public void setMaturityRating(string maturityRating)
		{
			this.maturityRating = maturityRating;
			PokktNativeExtension.PerformOperation(PokktOperations.SetMaturityRating, maturityRating);
		}
	}
}

