// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///


public static class GPGSIds
{
        public const string achievement_prize_curator = "CgkI_cDS6q0UEAIQCg"; // <GPGSID>
        public const string achievement_claw_mania_professor = "CgkI_cDS6q0UEAIQFQ"; // <GPGSID>
        public const string achievement_my_first_collection = "CgkI_cDS6q0UEAIQCQ"; // <GPGSID>
        public const string achievement_papa_bear = "CgkI_cDS6q0UEAIQDw"; // <GPGSID>
        public const string achievement_rate_us = "CgkI_cDS6q0UEAIQAQ"; // <GPGSID>
        public const string achievement_first_prize = "CgkI_cDS6q0UEAIQBQ"; // <GPGSID>
        public const string achievement_sweet_tooth = "CgkI_cDS6q0UEAIQEg"; // <GPGSID>
        public const string achievement_the_animal_lover = "CgkI_cDS6q0UEAIQEw"; // <GPGSID>
        public const string achievement_the_badass = "CgkI_cDS6q0UEAIQDg"; // <GPGSID>
        public const string achievement_the_more_the_better = "CgkI_cDS6q0UEAIQCA"; // <GPGSID>
        public const string achievement_our_big_fan = "CgkI_cDS6q0UEAIQFA"; // <GPGSID>
        public const string achievement_serious_grabber = "CgkI_cDS6q0UEAIQCw"; // <GPGSID>
        public const string achievement_the_sporty = "CgkI_cDS6q0UEAIQEA"; // <GPGSID>
        public const string achievement_aim_for_power = "CgkI_cDS6q0UEAIQDQ"; // <GPGSID>
        public const string achievement_the_spender = "CgkI_cDS6q0UEAIQBA"; // <GPGSID>
        public const string achievement_fancy_grabber = "CgkI_cDS6q0UEAIQDA"; // <GPGSID>
        public const string achievement_watch_ads = "CgkI_cDS6q0UEAIQAw"; // <GPGSID>
        public const string achievement_car_collector = "CgkI_cDS6q0UEAIQEQ"; // <GPGSID>
        public const string achievement_share_our_game = "CgkI_cDS6q0UEAIQAg"; // <GPGSID>
        public const string achievement_first_free_coins = "CgkI_cDS6q0UEAIQBw"; // <GPGSID>

}

